# Generated by Django 4.0.6 on 2022-09-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='comment_user',
        ),
    ]
