# Generated by Django 4.0.6 on 2022-09-14 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0003_rename_user_comment_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='bulletin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_bulletin', to='bulletin.bulletin'),
        ),
    ]
